#!/usr/bin/env bash
set -eo pipefail

wget https://dl.min.io/client/mc/release/linux-amd64/mc -O /bin/mc
chmod +x /bin/mc
chown slug:slug /app \
  /runner/init \
  /bin/get_object \
  /bin/normalize_storage
